Andromeda-labs/ECE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('core.urls' , namespace='core')),
    url(r'^api/', include('lab.urls', namespace='lab')),
    #url(r'^api-auth/', include('rest_framework.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

Andromeda-labs/core/urls.py
from django.conf.urls import url
from . import views
from lab.views import indexLab

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^historia-clinica/$', views.historiaClinicaView.as_view(), name='historia_clinica'),
    url(r'^laboratorio/$', indexLab, name='laboratorio'),
    #url(r'^paciente-create/$', views.createPaciente, name='paciente_create'),
    url(r'^pacientes/$', views.pacientesList.as_view(), name='pacientes_list'),
    url(r'^api/paciente-detail/(?P<pk>[0-9]+)/$', views.pacienteDetail.as_view(), name='paciente_detail'),
    url(r'^api/antecedentes/(?P<pk>[0-9]+)/$', views.antecedenteList.as_view(), name='antecedentes_detail'),
    url(r'^pacientes/detail/(?P<pk>[0-9]+)$', views.pacienteDetail2, name='paciente_detail2'),
]

Andromeda-labs/lab/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # API URLS
    url(r'^estudio-create/$', views.estudioCreateList.as_view(), name='estudio-create'),
    url(r'^estudio-detail/(?P<pk>[0-9]+)/$', views.estudioDetail.as_view(), name='estudio-detail'),
    url(r'^check-estudio/$', views.check_estudios.as_view(), name='check-estudio'),
    url(r'^get_estudios/(?P<pk>[0-9]+)/$', views.getPacienteEstudio.as_view(), name='get_paciente_estudios'),
]

ECE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('core.urls' , namespace='core')),
    #url(r'^api-auth/', include('rest_framework.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^accounts/register/$', views.uRegisterView, name='user_register'),
    url(r'^accounts/profile/(?P<pk>\d+)/$', views.userProfile, name='user_profile'),
]

Andromeda-labs/core/models.py
from django.db import models

# Create your models here.
class TimeStampedModel(models.Model):
    """
    this model contain created and updated timestamp
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

Andromeda-labs/historiaClinica/forms.py
from django import forms
from . import models

class pacienteForm(forms.ModelForm):
    
    class Meta:
        model = models.Paciente
        fields = ('first_name', 'last_name', 
                    'gender', 'birth_day', 
                    'phone_number', 'civil_status',
                    'religion', 'address', 'country', 'city', 'location',
                    'scholarship', 'ocupattion', 'ocupattion2', 'email')
    
    

Andromeda-labs/users/forms.py
from django import forms
from django.contrib.auth.models import User

class userRegistration(forms.ModelForm):
    password1 = forms.CharField(label='Contraseña', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Verificar contraseña', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', )

    def __init__(self, *args, **kwargs):
        super(userRegistration, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password1'] != cd['password2']:
            raise forms.ValidationError('Las contraseñas deben coincidir.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Ya existe un usuario registrado con este correo electrónico.')
        return data

    

Andromeda-labs/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from django.views import generic

from django.http import JsonResponse
from django.contrib import messages
from django.utils.decorators import method_decorator
from historiaClinica import models as modelsHC

from historiaClinica.forms import pacienteForm
from historiaClinica.serializers import pacienteSerializer, antecedenteSerializer
from .permissions import IsOwnerOrReadOnly
from .mixins import UserOwnerMixin, FormUserNeededMixin, LoginRequiredMixin

from rest_framework import generics
from rest_framework.permissions import IsAuthenticated

# Create your views here.

@login_required
def dashboard(request):
    return render(request, 'core/dashboard.html', {'section':'index'})

class historiaClinicaView(LoginRequiredMixin, generic.View):

    def get(self, request, *args, **kwargs):
        pacientes = modelsHC.Paciente.objects.all()
        return render(request, 'hiscli/index.html', {'pacientes':pacientes, 'section':'hiscli'})

from django.template.loader import render_to_string

class pacientesList(generics.ListCreateAPIView):
    queryset = modelsHC.Paciente.objects.all()
    serializer_class = pacienteSerializer
    permission_classes = (IsAuthenticated, )

    def list(self, request):
        queryset = self.get_queryset()
        serializer = pacienteSerializer(queryset, many=True)
        return Response(serializer.data)
    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status, permissions
from django.http import Http404
# class pacientesList(APIView):
#     """
#     Lista todos los pacientes o crea uno nuevo
#     """
#     def get(self, request, format=None):
#         pacientes = Paciente.objects.all()
#         serializer = pacienteSerializer(pacientes, many=True)
#         return Response(serializer.data)

#     def post(self, request, format=None):
#         serializer = pacienteSerializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save(user=self.request.user)
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# Inician las vistas del paciente
class pacienteDetail(APIView):

    def get_object(self, pk):
        try:
            return modelsHC.Paciente.objects.get(pk=pk)
        except modelsHC.Paciente.DoesNotExist:
            raise Http404
    def get(self, request, pk, format=None):
        paciente = self.get_object(pk)
        serializer = pacienteSerializer(paciente)
        return Response(serializer.data)

    def put(self, request, pk, format=None):
        paciente = self.get_object(pk)
        serializer = pacienteSerializer(paciente, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk, format=None):
        paciente = self.get_object(pk)
        paciente.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)
# TERMINAN VISTAS DEL PACIENTE
# INCIA VISTAS DE ANTECEDENTES DEL PACIENTE
@login_required
def pacienteDetail2(request, pk=None):
    try:
        paciente = None
        paciente = get_object_or_404(modelsHC.Paciente, pk=pk)
    except modelsHC.Paciente.DoesNotExist:
        pass
    try:
        antecedentes = None
        antecedentes = modelsHC.Antecedentes.objects.get(paciente=paciente)
    except modelsHC.Antecedentes.DoesNotExist:
        pass
    try:
        ahf = None
        ahf = modelsHC.AntecedentesHeredofamiliares.objects.get(paciente=paciente)
    except modelsHC.AntecedentesHeredofamiliares.DoesNotExist:
        pass
    try:
        ap = None
        ap = modelsHC.antecedentesPersonales.objects.get(paciente=paciente)
    except modelsHC.antecedentesPersonales.DoesNotExist:
        pass
    try:
        fisio = None
        fisio = modelsHC.Fisiologicos.objects.get(antecedente=ap)
    except modelsHC.Fisiologicos.DoesNotExist:
        pass
    try:
        pato = None
        pato =modelsHC.Patologicos.objects.get(antecedente=ap)
    except modelsHC.Patologicos.DoesNotExist:
        pass
    try:
        signos = None
        signos = modelsHC.signosVitales.objects.get(paciente=paciente)
    except modelsHC.signosVitales.DoesNotExist:
        pass
    return render(request, 'hiscli/paciente_detail.html', {'paciente':paciente,
                                            'antecedentes':antecedentes,
                                            'ahf':ahf,
                                            'ap':ap, 'fisio':fisio, 'pato':pato,
                                            'signos':signos})
# agregar y listar antecedentes
class antecedenteList(APIView):
    """
    Lista todos los antecedentes o crea uno nuevo
    """
    def get_object(self, pk):
        try:
            paciente = modelsHC.Paciente.objects.get(pk=pk)
            return paciente
        except modelsHC.Antecedentes.DoesNotExist:
            raise Http404
    def get(self, request, pk, format=None):
        paciente = self.get_object(pk)
        antecedentes = paciente.antecedentes_set.all()
        serializer = antecedenteSerializer(antecedentes, many=True)
        return Response(serializer.data)

Andromeda-labs/historiaClinica/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings
from django.contrib.auth.models import User
from django.views.generic import View

# Create your views here.

Andromeda-labs/lab/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404

from rest_framework import viewsets
from .serializers import estudioSerializer, estudioListSerializer
from .models import Estudio, EstudioList

from rest_framework.permissions import IsAuthenticated
from rest_framework import generics, status
from rest_framework.response import Response
from rest_framework.views import APIView
# Create your views here.

### API VIEWS ###
class estudioCreateList(generics.ListCreateAPIView):
    queryset = Estudio.objects.all()
    serializer_class = estudioSerializer
    permission_classes = (IsAuthenticated, )

    def list(self, request):
        queryset = self.get_queryset()
        serializer = estudioSerializer(queryset, many=True)
        return Response(serializer.data)

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

class estudioDetail(APIView):

    def get_object(self, pk):
        try:
            return Estudio.objects.get(pk=pk)
        except Estudio.DoesNotExist:
            raise Http404
    def get(self, request, pk, format=None):
        estudio = self.get_object(pk)
        serializer = estudioSerializer(estudio)
        return Response(serializer.data)
    def put(self, request, pk, format=None):
        estudio = self.get_object(pk)
        serializer = estudioSerializer(estudio, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    def delete(self, request, pk, format=None):
        estudio = self.get_object(pk)
        estudio.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class check_estudios(generics.ListAPIView):
    queryset = EstudioList.objects.all()
    serializer_class = estudioListSerializer
    permission_classes = (IsAuthenticated, )

    def list(self, request):
        queryset = self.get_queryset()
        serializer = estudioListSerializer(queryset, many=True)
        return Response(serializer.data)

class getPacienteEstudio(generics.ListAPIView):
    serializer_class = estudioSerializer
    permission_classes = (IsAuthenticated, )

    def get_queryset(self):
        paciente = self.kwargs.get('pk')
        return Estudio.objects.filter(paciente=paciente)
### NORMAL DJANGO VIEWS ###
from django.http import JsonResponse

from django.contrib.auth.views import login_required
@login_required
def indexLab(request):
    estudios = EstudioList.objects.all()
    return render(request, 'lab/laboratorio.html', {'section':'lab', 'estudios':estudios})

Andromeda-labs/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .forms import userRegistration
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
# Create your views here.
# class uRegisterView(View):

#     def get(self, request, *args, **kwargs):
#         form = userRegistration()
#         return render(request, 'registration/register.html', {'form':form})
    
#     def post(self, request, *args, **kwargs):
#         form = userRegistration(request.POST or None)
#         if form.is_valid():
#             #creamos un nuevo objeto usuario
#             new_user = form.save(commit=False)
#             #insertamos la contraseña
#             new_user.set_password(form.cleaned_data['password'])
#             #guardamos el objeto usuario
#             new_user.save()
#             #retornamos la url de éxito o un html
#             messages.success(request, '¡Se ha registrado exitosamente!')
#             return render(request, 'registration/register_done.html', {'form':form})

def uRegisterView(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('/')
    else:
        if request.method == 'POST':
            form = userRegistration(request.POST or None)
            if form.is_valid():
                new_user = form.save(commit=False)
                new_user.set_password(form.cleaned_data['password1'])
                new_user.save()
                messages.success(request, '¡Se ha registrado exitosamente!')
                return render(request, 'registration/register_done.html', {'form':form})
        else:
            form = userRegistration()
        return render(request, 'registration/register.html', {'form':form})

from django.core.exceptions import ObjectDoesNotExist

@login_required
def userProfile(request, pk):

    try:
        user = get_object_or_404(User, pk=pk)
        return render(request, 'profile/profile.html', {'user':user})
    except ObjectDoesNotExist:
        raise http404
        #return render(request, 'extra/404.html')

Andromeda-labs/templates/global/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <title> {% block title %} {% endblock title %} </title>
</head>
<body>
    {% include 'global/nav.html' %}
    {% include 'global/messages.html' %}
    {% block content %}

    {% endblock content %}

    {% include 'global/footer.html' %}
</body>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/mdb.min.js' %}"></script>
<script src="{% static 'js/csrf.js' %}"></script>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
{% block js %} {% endblock %}
</html>

Andromeda-labs/templates/global/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

Andromeda-labs/templates/global/nav.html
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark indigo fixed-top">

        <!-- Navbar brand -->
        <a class="navbar-brand" href="#">Andrómeda Labs</a>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <!-- Links -->
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                <li {%if section == 'index'%} class="nav-item active" {%else%}  class="nav-item"{%endif%}>
                        <a class="nav-link" href="{% url 'core:dashboard' %}">Inicio</a>
                    </li>
                    <li {%if section == 'hiscli'%} class="nav-item active" {%else%}  class="nav-item"{%endif%}>
                      <a class="nav-link" href="{% url 'core:historia_clinica' %}">Historial Clínico</a>
                    </li>
                    <li {% if section == 'lab' %} class="nav-item active" {% else %} class="nav-item" {%endif%}>
                        <a class="nav-link" href="{% url 'core:laboratorio' %}">Laboratorio</a>
                    </li>
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{request.user.username}}</a>
                        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="#">Perfil</a>
                            <a class="dropdown-item" href="#">Configuración</a>
                            <hr>
                            <a class="dropdown-item" href="{% url 'auth:logout' %}">Cerrar sesión</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:user_register' %}">Registrate</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'auth:login' %}" class="nav-link">Entrar</a>
                    </li>
                </ul>
                {% endif %}
            <!-- Links -->

        </div>
        <!-- Collapsible content -->

    </nav>
<style type="text/css">
    body {
            padding-top: 60px;
          }
    @media (min-width: 992px) {
        body {
                padding-top: 56px;

        }
</style>