Andromeda-labs/ECE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('core.urls' , namespace='core')),
    url(r'^api/', include('lab.urls', namespace='lab')),
    #url(r'^api-auth/', include('rest_framework.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

ECE/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('users.urls', namespace='users')),
    url(r'^', include('core.urls' , namespace='core')),
    #url(r'^api-auth/', include('rest_framework.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

core/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^historia-clinica/$', views.historiaClinicaView.as_view(), name='historia_clinica'),
    #url(r'^paciente-create/$', views.createPaciente, name='paciente_create'),
    url(r'^pacientes/$', views.pacientesList.as_view(), name='pacientes_list'),
    url(r'^api/paciente-detail/(?P<pk>[0-9]+)/$', views.pacienteDetail.as_view(), name='paciente_detail'),
    url(r'^api/antecedentes/(?P<pk>[0-9]+)/$', views.antecedenteList.as_view(), name='antecedentes_detail'),
    url(r'^pacientes/detail/(?P<pk>[0-9]+)$', views.pacienteDetail2, name='paciente_detail2'),
]

historiaClinica/models.py
from django.db import models
from core.models import TimeStampedModel
from django.conf import settings
# Create your models here.
GENDER_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
    ('O', 'Otro'),
)
CIVIL_STATUS_CHOICES = (
    ('C', 'Casado(a)'),
    ('S', 'Soltero(a)'),
    ('D', 'Divorciado(a)'),
)
import uuid
# Modelo de Paciente, sera la clase Padre y solo se llamará a las demás clases
# desde su llave foranea 'pk - id'
# Modelo de los datos generales del paciente
class Paciente(TimeStampedModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    udi = models.UUIDField(default=uuid.uuid4, editable=False)
    first_name = models.CharField('Nombre(s)', max_length=100)
    last_name = models.CharField('Apellidos', max_length=100)
    gender = models.CharField('Sexo', max_length=20, choices=GENDER_CHOICES)
    birth_day = models.DateField('Fecha de nacimiento', blank=True, null=True)
    phone_number = models.CharField('Número de telefono', max_length=13)
    civil_status = models.CharField('Estado civil', max_length=20, choices=CIVIL_STATUS_CHOICES)
    religion = models.CharField('Religión', max_length=50, blank=True)
    address = models.CharField('Dirección', max_length=150)
    country = models.CharField('Pais', max_length=40)
    city = models.CharField('Ciudad', max_length=60)
    location = models.CharField('Poblado/Municipio', max_length=100)
    scholarship = models.CharField('Escolaridad', max_length=60, blank=True)
    ocupattion = models.CharField('Ocupación', max_length=100, blank=True)
    ocupattion2 = models.CharField('Otra ocupación', max_length=100, blank=True, null=True)
    email = models.EmailField('Correo Electrónico', max_length=50)

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_full_name(self):
        return '%s %s' % (self.first_name, self.last_name)

    def get_age(self):
        import datetime
        return int( (datetime.date.today() - self.birth_day).days / 365.25 )
    class Meta:
        permissions = (
            ('can_create_paciente', 'Puede crear o dar de altu un paciente'),
            ('can_delete_paciente', 'Puede eliminar pacientes'),
            ('can_update_paciente', 'Puede actualizar pacientes'),
        )

# Modelo Antecedentes del paciente, la cual almacenara toda la información
# acerca de enfermedades pasadas de él o de sus familiares, así como inmunizaciones
# hábitos y alergias
class Antecedentes(TimeStampedModel):
    """
    Modelo de motivo y antecedentes de la enfermedad presentada en el momento de
    la consulta
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True) #se cambió)
    motivo = models.TextField('Motivo de la consulta')
    antecedentes = models.TextField('Antecedentes de la enfermedad actual', blank=True, null=True)

    def __str__(self):
        return 'Antecedentes del Paciente - %s' % (self.paciente.get_full_name())

CAUSA_CHOICES = (
    ('V', 'Vivos'),
    ('F', 'Fallecidos'),
)
TRUE_FALSE_CHOICES = (
    ('P', 'Positivo'),
    ('N', 'Negativo'),
)
class AntecedentesHeredofamiliares(TimeStampedModel):
    """
    Modelo de Antecedentes del mismo paciente y/o de sus familiares
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True) #se cambió)
    parents = models.CharField('Padres', max_length=20, choices=CAUSA_CHOICES)
    parents_causa = models.CharField('Causa de muerte', max_length=150, blank=True, null=True, default='Vivos')
    brothers = models.CharField('Hermanos', max_length=20, choices=CAUSA_CHOICES)
    brothers_causa = models.CharField('Causa de muerte', max_length=150, blank=True, null=True, default='Vivos')
    sons = models.CharField('Hijos', max_length=20, choices=CAUSA_CHOICES)
    sons_causa = models.CharField('Causa de muerte', max_length=150, blank=True, null=True, default='Vivos')
    DBT = models.CharField('Diabetes mellitus', max_length=20, choices=TRUE_FALSE_CHOICES)
    HTA = models.CharField('HiperTensión Arterial', max_length=20, choices=TRUE_FALSE_CHOICES)
    TBC = models.CharField('Tuberculosis', max_length=20, choices=TRUE_FALSE_CHOICES)
    GM = models.CharField('Gemelar', max_length=20, choices=TRUE_FALSE_CHOICES)
    other = models.CharField('Otra(s)', max_length=200, blank=True, null=True)

    def __str__(self):
        return 'Antecedentes Heredofamiliares de - %s' % (self.paciente.get_full_name())

class antecedentesPersonales(TimeStampedModel):
    """
    Modelo de los antecedentes personales del paciente
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True) #se cambió)
    alcohol = models.CharField('Alcohol', max_length=100, blank=True)
    tabaco = models.CharField('Tabaco', max_length=100, blank=True)
    drogas = models.CharField('Drogas', max_length=100, blank=True)
    infusiones = models.CharField('Infusiones', max_length=100, blank=True)

    def __str__(self):
        return 'Antecedentes personales de %s' % (self.paciente.get_full_name())

class Fisiologicos(TimeStampedModel):
    """
    Antecedentes personales Fisiologicos del paciente, este modelo hereda de
    antecedentesPersonales
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    antecedente = models.ForeignKey(antecedentesPersonales, on_delete=models.CASCADE, blank=True, null=True) #se cambió)
    dipsia = models.CharField('Dipsia', max_length=250, blank=True)
    diuresis = models.CharField('Diuresis', max_length=250, blank=True)
    catarsis = models.CharField('Catarsis', max_length=250, blank=True)
    somnia = models.CharField('Somnia', max_length=250, blank=True)
    others = models.CharField('Otros', max_length=250, blank=True)

    def __str__(self):
        return 'Antecedentes personales fisiológicos de %s' % (self.antecedente.paciente.get_full_name())

class Patologicos(TimeStampedModel):
    """"
    Antecedentes personales patológicos del paciente, esta modelo hereda de
    antecedentesPersonales
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    antecedente = models.ForeignKey(antecedentesPersonales, on_delete=models.CASCADE, null=True) #se cambió)
    infancia = models.CharField('Infancia', max_length=200)
    adulto = models.CharField('Adulto', max_length=200)
    DBT = models.CharField('Diabetes mellitus', max_length=20, choices=TRUE_FALSE_CHOICES)
    HTA = models.CharField('HiperTensión Arterial', max_length=20, choices=TRUE_FALSE_CHOICES)
    TBC = models.CharField('Tuberculosis', max_length=20, choices=TRUE_FALSE_CHOICES)
    GM = models.CharField('Gemelar', max_length=20, choices=TRUE_FALSE_CHOICES)
    other = models.CharField('Otra(s)', max_length=200, blank=True, null=True)
    quirurgicos = models.CharField('Quirúrgicos', max_length=200)
    traumalogicos = models.CharField('Traumalógicos', max_length=200)
    alergicos = models.CharField('Alérgicos', max_length=200)
    others = models.CharField('Otra(s)', max_length=200, blank=True, null=True)

    def __str__(self):
        return 'Antecedentes personales patológicos de %s' % (self.antecedente.paciente.get_full_name())

class signosVitales(TimeStampedModel):
    """
    Modelo de signos vitales del paciente
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE, null=True) #se cambió
    pulso = models.FloatField('Frecuencia cardiaca por minuto', default=0.0)
    temperatura = models.FloatField('Temperatura en °C', default=0.0)
    respiracion = models.PositiveSmallIntegerField('Respiración', default=0)
    arterial = models.CharField('Presión Arterial', max_length=7, default='0/0')

    def __str__(self):
        return 'Signos vitales del paciente - %s' % (self.paciente.get_full_name())

    def get_pulso(self):
        if self.pulso >= 60 and self.pulso <= 80:
            return 0
        elif self.pulso >= 80 and self.pulso <= 100:
            return 1
        elif self.pulso > 100:
            return 2
        return self.pulso

users/models.py
from django.db import models
from core.models import TimeStampedModel
from django.conf import settings
from django.core.urlresolvers import reverse
# Create your models here.
GENDER_CHOICES = (
    ('M', 'Masculino'),
    ('F', 'Femenino'),
)
CIVIL_STATUS_CHOICES = (
    ('C', 'Casado(a)'),
    ('S', 'Soltero(a)'),
    ('D', 'Divorciado(a)'),
)
class userProfile(TimeStampedModel):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    address = models.CharField('Dirección', max_length=100)
    phone_number = models.CharField('Número de telefono', max_length=13)
    gender = models.CharField('Sexo', choices=GENDER_CHOICES, max_length=15)
    birth_day = models.DateField('Fecha de nacimiento', blank=True, null=True)
    matricula = models.CharField('Cedula/licencia de trabajo', max_length=25)
    civil_state = models.CharField('Estado civil', max_length=20, choices=CIVIL_STATUS_CHOICES)
    country = models.CharField('Pais', max_length=40)
    city = models.CharField('Ciudad', max_length=60)
    location = models.CharField('Poblado/Municipio', max_length=100)
    Nacionality = models.CharField('Nacionalidad', max_length=60)
    especialidad = models.CharField('Especialidad', max_length=100, blank=True, null=True)
    especialidad1 = models.CharField('Especialidad', max_length=100, blank=True, null=True)
    especialidad2 = models.CharField('Especialidad', max_length=100, blank=True, null=True)
    is_doctor = models.BooleanField('¿Es médico?', default=False)
    is_nurse = models.BooleanField('¿Es enfermera?', default=False)

    def __str__(self):
        return 'Perfil de - %s' % (self.user.get_full_name())
    
    def get_absolute_url(self):
        if not self.matricula:
            return reverse("user_profile", kwargs={'pk': self.user.pk})
        return reverse('user_profile', kwargs={'matricula': self.matricula})
        

    def set_doctor(self):
        self.is_doctor = True
        self.is_nurse = False
        self.save()
    def set_nurse(self):
        self.is_doctor = False
        self.is_nurse = True
        self.save()

templates/hiscli/index.html
{% include "global/base.html" %}

<!--{% block title %} Andromeda Labs {% endblock %} -->
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <h1 class="page-header">Pacientes - </h1>
            <p>
<!-- Button trigger modal -->
            <button type="button" class="btn btn-success" data-toggle="modal" data-target="#exampleModal">
                Nuevo paciente
            </button>
            </p>
                    <!-- Search form -->
            <form class="form-inline">
                <input class="form-control" type="text" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-indigo btn-sm"><i class="fa fa-search"></i></button>
            </form>
<!--Table-->
<table class="table" id="table-results">

        <!--Table head-->
        <thead class="mdb-color darken-3">
            <tr class="text-white">
                <th>#</th>
                <th>Nombre(s)</th>
                <th>Apellidos</th>
                <th>Sexo</th>
                <th>Telefono</th>
                <th>Dirección</th>
                <th>Localización</th>
                <th>E-mail</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <!--Table head-->

        <!--Table body-->
        <tbody>
          {% include "hiscli/includes/partial_paciente_list.html" %}
        </tbody>
        <!--Table body-->
    </table>
    <!--Table-->

    <!-- Modal create paciente -->
    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Agregar un paciente nuevo</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="savePaciente" action="{% url 'core:pacientes_list' %}" method="post" >{%csrf_token%}
                            <input type="text" required name="first_name"
                            class="form-control" id="id_first_name" placeholder="Nombre(s)">

                            <input type="text" required name="last_name" class="form-control"
                            id="id_last_name" placeholder="Apellidos">

                            <label for="id_gender">Selecciona el sexo</label>
                            <select class="form-control" name="gender" id="id_gender" required>
                                <option value="F">Femenino</option>
                                <option value="M">Masculino</option>
                                <option value="O">Otro</option>
                            </select>

                            <h4>Edad</h4>
                            <div class="input-append date" id="dp3" data-date="12-02-2012" data-date-format="yyyy-mm-dd">
                              <input name="birth_day" class="span2" size="16" type="text" value="12-02-2012">
                              <span class="add-on"><i class="icon-th"></i></span>
                            </div>

                            <label for="id_phone_number">Número de telefono</label>
                            <input type="text" maxlength="13" required class="form-control"
                            placeholder="Número de telefono" name="phone_number" id="id_phone_number">

                            <label for="id_civil_status">Estado civil</label>
                            <select name="civil_status" id="id_civil_status" required class="form-control">
                                <option value="C">Soltero</option>
                                <option value="S">Casado</option>
                                <option value="D">Divorciado</option>
                            </select>

                            <label for="id_religion">Religión</label>
                            <select name="religion" id="id_religioon" required class="form-control">
                                <option value="Ninguna">Ninguna</option>
                                <option value="Catolicísmo">Catolicísmo</option>
                                <option value="Cistrianísmo">Cristianísmo</option>
                                <option value="Islam">Islam</option>
                                <option value="Judaísmo">Judaísmo</option>
                                <option value="Otra">Otra</option>
                            </select>

                            <input type="text" placeholder="Dirección" required class="form-control"
                            id="id_address" name="address">

                            <input type="text" placeholder="País" required class="form-control"
                            id="id_country" name="country">

                            <input type="text" placeholder="Ciudad" required class="form-control"
                            id="id_city" name="city">

                            <input type="text" placeholder="Localidad/municipio" required class="form-control"
                            id="id_location" name="location">

                            <label for="id_scholarship">Ultimo grado de estudios</label>
                            <select name="scholarship" id="id_scholarship" required class="form-control">
                                <option value="Primaria">Primaria</option>
                                <option value="Secundaria">Secundaria</option>
                                <option value="Preparatoria">Preparatoria</option>
                                <option value="Carrera universitaria">Universidad</option>
                                <option value="Otro">Otro</option>
                            </select>

                            <input type="text" required class="form-control" placeholder="Ocupación"
                            id="id_ocupattion" name="ocupattion">

                            <input type="text" class="form-control" placeholder="Otra ocupación"
                            id="id_ocupattion2" name="ocupattion2">

                            <input type="email" required class="form-control" placeholder="E-mail"
                            id="id_email" name="email">
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <input type="submit" class="btn btn-primary" value="Guardar" id="btnGuardarPaciente">
                </div>
            </div>
        </div>
    </div>


<script type="text/javascript">

$("#dp3").datepicker();
$("#btnGuardarPaciente").click(function() {
    $.ajax({
        url: '{% url "core:pacientes_list" %}',
        type: 'POST',
        data: $("#savePaciente").serialize(),
        dataType: 'json',
        success: function(data) {
            console.log(data);
            alert("Paciente agregado!.");
            $("#exampleModal").modal('toggle');
            if (data) {
              var len = data.length;
              var txt = "";
              if (len > 0) {
                for (var i = 0; i<len; i++) {
                  if (data[i].id && data[i].first_name) {
                    txt += "<tr><td>" + data[i].id + "</td><td>" + data[i].first_name + "</tr><td>";
                  }
                }
                if (txt != "") {
                  $("#table-results tbody").append(txt);
                }
              }
            }
        },
        error: function(xhr, resp, text) {
            console.log(xhr, resp, text);
        }
    });
});

  $(".btnDeletePaciente").click(function(e){
      e.preventDefault();
      var pkg = $(this).attr("name");
      $.ajax({
        type: 'DELETE',
        url: '/api/paciente-detail/' + pkg,
        success: function() {
          alert("Paciente eliminado.");
          location.href="/historia-clinica/";
        },
        error: function () {
          console.log("error en algún lado");
        }
      });

  });
</script>

<style type="text/css">
    .hide{
        display: none;
    }
    label{margin-left: 20px;}
#datepicker{width:180px; margin: 0 20px 20px 20px;}
#datepicker > span:hover{cursor: pointer;}
</style>
{% endblock content %}